### ISSUE TITLE
Insert missing text into methods 

### ISSUE THREAD

**Issue by egouldo** [egouldo/ManyAnalysts#20]
> Next, we will assess the relationship between the inclusion of random effects in the analysis and the deviation from the mean effect size. We anticipate that most analysts will use random effects in a mixed model framework, but if we are wrong, we want to evaluate the differences in outcomes when using random effects versus not using random effects. Thus if there are at least 5 analyses that do and 5 analyses that do not include random effects, we will add a binary predictor variable random effects included (yes/no) to our set of univariate analyses and will add this predictor variable to our multivariate model described below.

- [ ] update tense

**Comment by parkerth** [comment]
This had already been updated.
