### ISSUE TITLE
C.4.1 Effect Sizes dev ~ distinctiveness missing

### ISSUE THREAD

**Issue by egouldo** [egouldo/ManyAnalysts#24]
In the Supp Mat (SM3_ExplainingDeviation.qmd), Subsection C.4.1 Effect Sizes (deviation scores as explained by distinctiveness of variables in each analysis) is empty...? 

Is this because this content occurs elsewhere in the manuscript?

**Comment by egouldo** [comment]
- [x] @parkerth found it included in main text.
- [x] @egouldo to remove sub-header C.4.1 from SM3

**Comment by hannahsfraser** [comment]
Done
