### ISSUE TITLE
Remove mention of Sorensen's index from table C3 caption

### ISSUE THREAD

**Issue by egouldo** [egouldo/ManyAnalysts#26]
- [ ] Model not included in that parameter table, so remove from caption. 
- [ ] But check that model parameter estimates for Sorensen's models are included _somewhere_ in that document.

**Comment by parkerth** [comment]
Unfortunately, I cannot solve this issue myself at this time.

current table caption:
"Table C.3: Parameter estimates for univariate models of Box-Cox transformed deviation from the mean yi estimate as a function of categorical peer-review rating, continuous peer-review rating, and Sorensen’s index for blue tit and Eucalyptus analyses, and also for the inclusion of random effects for Eucalyptus analyses. "

So, there are two things mentioned in the caption that are not in the table.
1. Sorensen's index for both Euc and BT for yi
2. Inclusion of random effects for Euc for yi

Neither of these things are present in any other table. So we have two choices. We could either
a. add these things to this table 
or
b. create one or two new tables.

I am leaving the table caption as is right now until we decide which path to take.

**Comment by egouldo** [comment]
Thanks Tim, I couldn't find them either, but wasn't sure if I had overlooked them. I reckon we:

- [ ] include these analyses in this table rather than making a new table. Either myself or @hannahsfraser could probably do that part.

**Comment by hannahsfraser** [comment]
I have attempted a fix of this but cant test it at the moment. See commit #66

**Comment by egouldo** [comment]
Closing, fixed in #66
