### ISSUE TITLE
need cross-reference and or label for additional collinearity forest plot

### ISSUE THREAD

**Issue by parkerth** [egouldo/ManyAnalysts#28]
https://github.com/egouldo/ManyAnalysts/blob/28c4a40fa016deae5837cf59b2b22f8e18b8f170/index.qmd#L3789\

I included a placeholder citation for the new forest plot that excludes the effects from blue tit analyses containing the two highly collinear predictors. 
This placeholder is "(@fig-forest-plot-?????)"

**Comment by egouldo** [comment]
Great, thank you onto it.

**Comment by egouldo** [comment]
not yet fixed:

`WARNING: index.html: Unable to resolve crossref @fig-forest-plot` on `quarto::quarto_render()`

**Comment by egouldo** [comment]
Related to #27

**Comment by egouldo** [comment]
@parkerth or @hannahsfraser could you help with this task? and whoever gets there first, assign your self to the issue please :) 

- [ ] locate plot being referenced, does its ref label match the current cross-ref ?
- [ ] If not, make sure that both the label for the plot, and the cross-reference itself match (note that the cross-references should have the `@` symbol preceding it.
- [ ] Perhaps I've duplicated `@fig-forest-plot` label ?? Should probably be specific, so append `-collinearity` or similar.

**Comment by parkerth** [comment]
I'm not sure what the problem is here. 
In the rendered main text, the link to the figure works. 
That link is:
@fig-forest-plot-Zr-collinear-rm-subset

and in the supplement the label is:
fig-forest-plot-Zr-collinear-rm-subset

I am not closing this issue because I am concerned that maybe I am missing whatever the problem is. But if I am not missing it, then this issue should be closed.

**Comment by egouldo** [comment]
> I'm not sure what the problem is here. In the rendered main text, the link to the figure works. That link is: @fig-forest-plot-Zr-collinear-rm-subset
> 
> and in the supplement the label is: fig-forest-plot-Zr-collinear-rm-subset
> 
> I am not closing this issue because I am concerned that maybe I am missing whatever the problem is. But if I am not missing it, then this issue should be closed.

Thanks Tim, I suspect it will go away when we re-render it (currently the auto-render in the GitHub cloud and on my local machine is failing due to some bugs I'm working on fixing on other branches than main). Will leave open for now.

**Comment by hannahsfraser** [comment]
I think this is fixed... but I haven't merged my pull requests in
