### ISSUE TITLE
citation problem

### ISSUE THREAD

**Issue by parkerth** [egouldo/ManyAnalysts#29]
https://github.com/egouldo/ManyAnalysts/blob/28c4a40fa016deae5837cf59b2b22f8e18b8f170/index.qmd#L2141

For some reason, in the rendered version, two of Shinichi's citations are including his first name in the rendered text. In this line, it appears as:
linear models [GLMs; Shinichi Nakagawa and Cuthill (2007).

Shinichi's 2022 paper also has this problem. I have looked that the citations in the .bib file, and I cannot see any difference in formatting compared to other citations. I have not seen this problem arise for any other citations.

**Comment by egouldo** [comment]
NB might be in the grateful .bib file which contains refs to pkgs. @egouldo to check

**Comment by parkerth** [comment]
I looked at this before and have now looked at this again. There is no difference in the .bib code that I could find for this reference vs. others that I can see. 
The references.bib code is where this reference is.
grateful.bib does not contain this reference (Nakagawa and Cuthill 2007)

Maybe we just correct this by hand in Word in the submitted version

**Comment by egouldo** [comment]
Yup, this is definitely not an issue with our cross-references / citations / .bib files, but is  probably a quarto / pandoc processing bug, e.g.: https://github.com/quarto-dev/quarto-cli/issues/10105.

I agree, let's leave it for now in the html, and we will update it in the word document. I've moved it into the 'publication' milestone as opposed to the 'respond peer review comments' milestone, if we really wanted to chase it up and were twiddling our hands down the track.

**Comment by egouldo** [comment]
I had an idea, given that this is a bug in https://github.com/quarto-dev/quarto-cli, I think we can just edit the bibtex itself to remove Shinichi's first name from the .bib entry.

Also I noticed a similar issue with first author J.J. Allaire entry.
