### ISSUE TITLE
to clarify why AllTeams is +28

### ISSUE THREAD

**Issue by egouldo** [egouldo/ManyAnalysts#37]
Where did this figure come from??

`r All_Teams+28` call in Summary Statistics section

**Comment by egouldo** [comment]
Hey @hannahsfraser just seeking clarification on this

**Comment by hannahsfraser** [comment]
28 teams had analyses were excluded way early in the process so they aren't in any of the bits where we add up numbers - I added them in manually

**Comment by egouldo** [comment]
Great, thanks for clarifying. would you mind adding a note here about where we can locate  the these if needed in the future / grounds for exclusion? low priority, just thought it would be good to log!
