### ISSUE TITLE
extra numbers - deletion needed

### ISSUE THREAD

**Issue by parkerth** [egouldo/ManyAnalysts#46]
https://github.com/egouldo/ManyAnalysts/blob/91ca56a15ab2630054e7391b9b90a2dc974feb65/index.qmd#L3508

In the render, this currently reads as:

 "For the Eucalyptus dataset, the meta-analytic mean shifted from -0.09, -0.17, -0.03 to -0.02 when effects from analyses rated as unpublishable were removed, and to -0.04 when effects from analyses rated, at least once, as unpublishable or requiring major revisions were removed."

There are too many numbers in that first list of numbers.

**Comment by hannahsfraser** [comment]
I think I need the packages to run to fix this. I suspect we just need to add an extra filter clause in because several results are being called by the current one... but I need to see the object it's pulling from to know how to do that

**Comment by egouldo** [comment]
Thanks @hannahsfraser The relevant chunk is:

https://github.com/egouldo/ManyAnalysts/blob/31412e08f674ca8e9f90339bfdd3ba1688e1b057/index.qmd#L3443-L3510

on branch [42-mv-fns-2-pkg](https://github.com/egouldo/ManyAnalysts/tree/42-mv-fns-2-pkg).

I think if you:


1. check out [42-mv-fns-2-pkg](https://github.com/egouldo/ManyAnalysts/tree/42-mv-fns-2-pkg) locally
2. pull / push to sync
3. run `renv::activate()/renv::restore()` to install all the relavant libraries in the renv
4. install latest ManyEcoEvo:: package with: `renv::install("egouldo/ManyEcoEvo@v2.3.0")` 

you should be able to get it to render.

Alternatively, you can download and load the latest ManYEcoEvo, mess around with the chunk code interactively, and post a solution here for me to upgrade, if that's easier!

And if you can't get it going with either of those, I'll come back to this later.

**Comment by hannahsfraser** [comment]
I'm sorry, Elliot. I cant seem to get the damn thing to work. renv::restore keeps failing so I cant seem to get all the packages I need. I'm going to have to put this back on your plate.

**Comment by egouldo** [comment]
No sweat Hannah, I’m sorry renv has been such a massive pain to work with!! I will consider switching to a different platform in the future I think.

Sent from my iPhone

On 27 Aug 2024, at 10:30 AM, Hannah Fraser ***@***.***> wrote:

﻿

I'm sorry, Elliot. I cant seem to get the damn thing to work. renv::restore keeps failing so I cant seem to get all the packages I need. I'm going to have to put this back on your plate.
