### ISSUE TITLE
Quarto cross-reference to code listing not rendering

### ISSUE THREAD

**Issue by parkerth** [egouldo/ManyAnalysts#49]
https://github.com/egouldo/ManyAnalysts/blob/91ca56a15ab2630054e7391b9b90a2dc974feb65/supp_mat/SM3_ExplainingDeviation.qmd#L1792

There is some sort of error here, leading to failure to fully render. As rendered, here is what it says:

"...delta method (Equation C.1 and ?lst-variance-box-cox)."

**Comment by hannahsfraser** [comment]
Couldn't work out why this was wrong - the syntax is fine. However, I dont think we need the reference because of the way it's described in text so I've just cut it - removing the problem
