### ISSUE TITLE
quarto cross-reference not rendering

### ISSUE THREAD

**Issue by parkerth** [egouldo/ManyAnalysts#50]
https://github.com/egouldo/ManyAnalysts/blob/91ca56a15ab2630054e7391b9b90a2dc974feb65/supp_mat/SM3_ExplainingDeviation.qmd#L1787

rendered as:

"As we describe in (box-weight-deviation?), for models of deviation..."

**Comment by hannahsfraser** [comment]
I may have fixed this but cant check because I cant render

**Comment by hannahsfraser** [comment]
Also see commit #72

**Comment by egouldo** [comment]
> I may have fixed this but cant check because I cant render

Thanks Hannah, I'll render on my computer and see what happens.

**Comment by egouldo** [comment]
Nice fix @hannahsfraser it renders :D
