### ISSUE TITLE
Wrap latex math words in \text{}

### ISSUE THREAD

**Issue by egouldo** [egouldo/ManyAnalysts#52]
For example: 

![image](https://github.com/user-attachments/assets/267973ff-634d-41fe-95bd-7a1e7fba605d)

There are several other locations where this is the case in SM3, possibly in other locations. 

Remember: inside captions and inside gt tables: need to escape the command, so write: `\\text{}`, elsewhere, just plain old `\text{}`

**Comment by hannahsfraser** [comment]
I cant find any examples of the words not being wrapped in \text{} in the index of SM3
