### ISSUE TITLE
table citation issue

### ISSUE THREAD

**Issue by parkerth** [egouldo/ManyAnalysts#53]
https://github.com/egouldo/ManyAnalysts/blob/0c3dfcca4fd434eaf1b7c6ae96f3270db7aca2a1/index.qmd#L2525C34-L2525C42

This line cites "@tbl-Table1". However, that table is not appropriate given the citation here. 
That table shows some summary info about features of the submitted analyses:
 "Table A.1: Summary of the number of analysis teams, total analyses, models with normal error distributions, mixed effects models, and models developed with Bayesian statistical methods for effect size analyses only (Zr) and out-of-sample prediction only (yi)." 

But it is cited as showing information about the subset of analyses that included sufficient info for inclusion:
"Effects included in only a subset of our meta-analyses provided sufficient information for inclusion in only that subset (see Table A.1)."

So, we could either just delete this citation OR we could create a new table that includes the exclusion/inclusion info

**Comment by egouldo** [comment]
Good pick up Tim.

I reckon we don't make a table, but we include some text in the relevant supp. mat. section that outlines the inclusions / exclusions. Calculation of the `total_usable_effects` vs. total submitted analyses should reveal which data frames contain the included subset (I think the full set is in `ManyEcoEvo$data[[1]]` and `ManyEcoEvo$data[[2]]` for the euc/bt datasets, and what we called 'usable effects' are in `ManyEcoEvo_results$effects_analysis[[1]]` and `ManyEcoEvo_results$effects_analysis[[2]]`. So to identify the excluded set we can either take the difference and list the identifiers in the supp. mat. or just explain that to readers and point them to those objects in the `ManyEcoEvo` package. 

Looping @hannahsfraser in, and assigning to her to action please!

**Comment by hannahsfraser** [comment]
fixed
