### ISSUE TITLE
gt tables rm scientific notation, or constrain to only large numbers at least!

### ISSUE THREAD

**Issue by egouldo** [egouldo/ManyAnalysts#65]
Get rid of scientific notation in tables:

![image](https://github.com/egouldo/ManyAnalysts/assets/8400682/ba3ab96c-ea85-4196-b3e9-5ec0e6afbe23)

41 becomes 4.1 x 10! for instance.

**Comment by hannahsfraser** [comment]
I cant seem to get this to work, sorry. I can turn it off for a whole table... but I cant seem to turn it off just for some numbers in the table

**Comment by egouldo** [comment]
No worries, I got it!
